import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "react-query";
import { Quiz } from "types";
import { API_URL } from "urls";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  const { data } = useQuery<Quiz[]>("quizzes", () =>
    fetch(`${API_URL}/quizzes`).then((res) => res.json())
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Eguzki Strive Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Eguzki Strive Challenge</h1>
      <p>
        Go to the admin page <Link href="/admin">here</Link>
      </p>
      <p>
        Take any of the tests here:
        <ul>
          {data?.map((quiz) => (
            <li key={quiz.id}>
              {quiz.name} :<Link href={`/quiz/${quiz.id}`}>here</Link>
            </li>
          ))}
        </ul>
      </p>
    </div>
  );
};

export default Home;
